// ScriptEngineLib.idl : IDL source for ScriptEngineLib
//

// This file will be processed by the MIDL tool to
// produce the type library (ScriptEngineLib.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(8062E631-FD53-4BB1-9631-24690B0A8846),
	version(1.0),
	helpstring("ScriptEngineLib 1.0 Type Library")
]
library ScriptEngineLib
{
	importlib("stdole2.tlb");

	//----------------------------------------------------------------------
	//
	//----------------------------------------------------------------------

	interface IScriptEngine;

	//----------------------------------------------------------------------
	//
	//----------------------------------------------------------------------

	[
		object,
		uuid(528B31E2-CA67-4B48-BE5F-BF546F3E1909),
		dual,
		nonextensible,
		helpstring("IScriptEngine Interface"),
		pointer_default(unique)
	]
	interface IScriptEngine : IDispatch{
		[id(1)] HRESULT Clear();
		[id(2)] HRESULT CoFree();
		[id(3)] HRESULT Evaluate([in] BSTR ScriptText, [in] BSTR Language, [out,retval] VARIANT* Result);
		[id(4)] HRESULT Execute([in] BSTR ScriptText, [in] BSTR Language);
		[id(5)] HRESULT Import([in] BSTR Path, [in, defaultvalue("")] BSTR Name, [in, defaultvalue("")] BSTR Language);
		[id(6)] HRESULT ImportScript([in] BSTR ScriptText, [in, defaultvalue("")] BSTR Context, [in, defaultvalue("")] BSTR Name, [in, defaultvalue("")] BSTR Language, [in, defaultvalue(2)] DWORD dwNameFlags);
		[id(7)] HRESULT RunScript([in] BSTR Path, [in,defaultvalue("")] BSTR Language);
		[id(8)] HRESULT SetItem([in] BSTR Name, [in] VARIANT* Object, [in, defaultvalue(2)] DWORD dwFlags, [out,retval] LONG* Index);
		[id(9)] HRESULT SetWindow([in] OLE_HANDLE hWnd);
		[id(10)] HRESULT AddGlobal([in] IDispatch* item);
	};

	//----------------------------------------------------------------------
	//
	//----------------------------------------------------------------------

	[
		uuid(CE3D5E24-E53D-4EF4-BB96-8C9AE966CB1F),
		helpstring("ScriptEngine Class")
	]
	coclass ScriptEngine
	{
		[default] interface IScriptEngine;
	};

};
